### ISSUE TITLE
Not able upload more than 10 items

### ISSUE THREAD

**Issue by jawadan** [imranhsayed/gatsby-woocommerce-themes#80]
It gives me "error timeout of 30000ms exceeded" when I try to upload more than 10 items, I am hosting WP on cheapest AWS lightsail plan. If I get faster plan will it solve the problem?

**Comment by jawadan** [comment]
I also tried to run it with hostinger's business plan, it was able to upload maximum 36 items. I guess it's the limit.

**Comment by hofdee** [comment]
try to increase the timeout to 120000ms on the gatsby config file

**Comment by jawadan** [comment]
> try to increase the timeout to 120000ms on the gatsby config file

It doesn't really work I guess, still showing the same error

**Comment by jawadan** [comment]
Here is what I have tried,  but it still throws error  gatsby-source-wordpress  Your wordpress server at http://my-web-url/graphql appears to be overloaded.

`resolve: `gatsby-source-wordpress-experimental`,
      options: {
        url: `${wordPressUrl}/graphql`,
        schema: {
	  perPage: 100,
          timeout: 1000000,
	  requestConcurrency: 50, 
          previewRequestConcurrency: 50,
        },`

**Comment by hofdee** [comment]
try also increasing the WP_MEMORY_LIMIT  on the wp_config.php file

**Comment by jawadan** [comment]
> try also increasing the WP_MEMORY_LIMIT on the wp_config.php file

I did everything as you instructed, and it actually deployed once with little over 50 products, but the feature deploys didn't go through.

`info  gatsby-source-wordpress  GraphQL vars: {"first":1200,"url":"https://my-web-url/graphql","after":null}
error  gatsby-source-wordpress  Your wordpress server at https://my-web-url/graphql appears to be overloaded.
Try reducing the requestConcurrency for content updates or the previewRequestConcurrency for previews:
{
  resolve: 'gatsby-source-wordpress-experimental',
  options: {
    schema: {
      requestConcurrency: 5, // currently set to undefined
      previewRequestConcurrency: 2, // currently set to undefined
    }
  },
}
The GATSBY_CONCURRENT_REQUEST environment variable is no longer used to control concurrency.
If you were previously using that, you'll need to use the settings above instead.
not finished source and transform nodes - 55.460s
not finished  gatsby-source-wordpress  fetching nodes - 55.399s - 107 total
not finished  gatsby-source-wordpress  PaColor - 55.396s
not finished  gatsby-source-wordpress  PaMetalColor - 55.396s
not finished Downloading remote files - 32.661s
not finished Generating image thumbnails - 32.490s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /node14/bin/node
Arguments: /vercel/.yarn/lib/cli.js build
Directory: /vercel/path0/site
Output:
info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-woocommerce-themes@2.0.1 build: `yarn workspace site build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatsby-woocommerce-themes@2.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /vercel/.npm/_logs/2021-09-25T18_21_02_854Z-debug.log
Error: Command "npm run build" exited with 1`

**Comment by jawadan** [comment]
> try also increasing the WP_MEMORY_LIMIT on the wp_config.php file

I did everything as you instructed, and it actually deployed once with little over 50 products, but the feature deploys didn't go through.

`
info  gatsby-source-wordpress  GraphQL vars: {"first":1200,"url":"https://my-web-url/graphql","after":null}<br>
error  gatsby-source-wordpress  Your wordpress server at https://my-web-url/graphql appears to be overloaded.<br>
Try reducing the requestConcurrency for content updates or the previewRequestConcurrency for previews:<br>
{<br>
  resolve: 'gatsby-source-wordpress-experimental',<br>
  options: {<br>
    schema: {<br>
      requestConcurrency: 5, // currently set to undefined<br>
      previewRequestConcurrency: 2, // currently set to undefined<br>
    }<br>
  },<br>
}<br>
The GATSBY_CONCURRENT_REQUEST environment variable is no longer used to control concurrency.<br>
If you were previously using that, you'll need to use the settings above instead.<br>
not finished source and transform nodes - 55.460s<br>
not finished  gatsby-source-wordpress  fetching nodes - 55.399s - 107 total<br>
not finished  gatsby-source-wordpress  PaColor - 55.396s<br>
not finished  gatsby-source-wordpress  PaMetalColor - 55.396s<br>
not finished Downloading remote files - 32.661s<br>
not finished Generating image thumbnails - 32.490s<br>
error Command failed with exit code 1.<br>
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.<br>
error Command failed.<br>
Exit code: 1<br>
Command: /node14/bin/node<br>
Arguments: /vercel/.yarn/lib/cli.js build<br>
Directory: /vercel/path0/site<br>
Output:<br>
info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.<br>
npm ERR! code ELIFECYCLE<br>
npm ERR! errno 1<br>
npm ERR! gatsby-woocommerce-themes@2.0.1 build: `yarn workspace site build`<br>
npm ERR! Exit status 1<br>
npm ERR! <br>
npm ERR! Failed at the gatsby-woocommerce-themes@2.0.1 build script.<br>
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.<br>
npm ERR! A complete log of this run can be found in:<br>
npm ERR!     /vercel/.npm/_logs/2021-09-25T18_21_02_854Z-debug.log<br>
Error: Command "npm run build" exited with 1<br>
`

**Comment by jawadan** [comment]
> try also increasing the WP_MEMORY_LIMIT on the wp_config.php file

I did everything as you instructed, and it actually deployed once with little over 50 products, but the feature deploys didn't go through.

`
 -  info  gatsby-source-wordpress  GraphQL vars: {"first":1200,"url":"https://my-web-url/graphql","after":null}
 -  error  gatsby-source-wordpress  Your wordpress server at https://my-web-url/graphql appears to be overloaded.
 -  Try reducing the requestConcurrency for content updates or the previewRequestConcurrency for previews:
 -  {
 -    resolve: 'gatsby-source-wordpress-experimental',
 -    options: {
 -      schema: {
 -        requestConcurrency: 5, // currently set to undefined
 -        previewRequestConcurrency: 2, // currently set to undefined
 -      }
 -    },
 -  }
 -  The GATSBY_CONCURRENT_REQUEST environment variable is no longer used to control concurrency.
 -  If you were previously using that, you'll need to use the settings above instead.
 -  not finished source and transform nodes - 55.460s
 -  not finished  gatsby-source-wordpress  fetching nodes - 55.399s - 107 total
 -  not finished  gatsby-source-wordpress  PaColor - 55.396s
 -  not finished  gatsby-source-wordpress  PaMetalColor - 55.396s
 -  not finished Downloading remote files - 32.661s
 -  not finished Generating image thumbnails - 32.490s
 -  error Command failed with exit code 1.
 -  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 -  error Command failed.
 -  Exit code: 1
 -  Command: /node14/bin/node
 -  Arguments: /vercel/.yarn/lib/cli.js build
 -  Directory: /vercel/path0/site
 -  Output:
 -  info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
 -  npm ERR! code ELIFECYCLE
 -  npm ERR! errno 1
 -  npm ERR! gatsby-woocommerce-themes@2.0.1 build: `yarn workspace site build`
 -  npm ERR! Exit status 1
 -  npm ERR! 
 -  npm ERR! Failed at the gatsby-woocommerce-themes@2.0.1 build script.
 -  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 -  npm ERR! A complete log of this run can be found in:
 -  npm ERR!     /vercel/.npm/_logs/2021-09-25T18_21_02_854Z-debug.log
 -  Error: Command "npm run build" exited with 1

`

**Comment by jawadan** [comment]
Now it gives me this

`

error Error: Request failed with status code 502
--
01:30:11.587 | at createError (/vercel/path0/node_modules/axios/lib/core/createError.js:16:15)
01:30:11.587 | at settle (/vercel/path0/node_modules/axios/lib/core/settle.js:17:12)
01:30:11.587 | at IncomingMessage.handleStreamEnd (/vercel/path0/node_modules/axios/lib/adapters/http.js:236:11)
01:30:11.587 | at IncomingMessage.emit (events.js:412:35)
01:30:11.588 | at endReadableNT (internal/streams/readable.js:1334:12)
01:30:11.588 | at processTicksAndRejections (internal/process/task_queues.js:82:21) {

`
