### ISSUE TITLE
Can not install theme in Gatsby 

### ISSUE THREAD

**Issue by zephyr2125** [imranhsayed/gatsby-woocommerce-themes#98]
I install this theme for my gatsby project .But when gatsby develop, it error in module "sharp" 
"Something went wrong installing the "sharp" module"

**Comment by AVert** [comment]
Traceback (most recent call last):
  File "/dpool/dev/web/gatsby/gatsby-woocommerce-themes/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/dpool/dev/web/gatsby/gatsby-woocommerce-themes/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/dpool/dev/web/gatsby/gatsby-woocommerce-themes/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/dpool/dev/web/gatsby/gatsby-woocommerce-themes/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "/dpool/dev/web/gatsby/gatsby-woocommerce-themes/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "/dpool/dev/web/gatsby/gatsby-woocommerce-themes/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2783, in Load
    variables, includes, depth, check, True)
  File "/dpool/dev/web/gatsby/gatsby-woocommerce-themes/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 399, in LoadTargetBuildFile
    includes, True, check)
  File "/dpool/dev/web/gatsby/gatsby-woocommerce-themes/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 271, in LoadOneBuildFile
    aux_data, includes, check)
  File "/dpool/dev/web/gatsby/gatsby-woocommerce-themes/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 308, in LoadBuildFileIncludesIntoDict
    LoadOneBuildFile(include, data, aux_data, None, False, check),
  File "/dpool/dev/web/gatsby/gatsby-woocommerce-themes/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 251, in LoadOneBuildFile
    None)
  File "/home/buddha/.node-gyp/18.16.1/include/node/common.gypi", line 1
    e_data_file_flag%': 1
                        ^
SyntaxError: EOL while scanning string literal
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/dpool/dev/web/gatsby/gatsby-woocommerce-themes/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.15.0-75-generic
gyp ERR! command "/home/buddha/.nvm/versions/node/v18.16.1/bin/node" "/dpool/dev/web/gatsby/gatsby-woocommerce-themes/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /dpool/dev/web/gatsby/gatsby-woocommerce-themes/node_modules/node-sass
gyp ERR! node -v v18.16.1
